### ISSUE TITLE
404 File not found

### ISSUE THREAD

**Issue by kaaatsu32329** [openrr/openrr-tutorial#13]
Now, we cannot access to the site when following link in README.

![Screenshot from 2023-03-31 15-46-57](https://user-images.githubusercontent.com/44460592/229044440-20f955e7-9da7-4a07-9181-7f361e94b878.png)

**Comment by kaaatsu32329** [comment]
> Books
You can read the book at the following links.

English: https://openrr.github.io/openrr-tutorial/en

Japanese: https://openrr.github.io/openrr-tutorial/ja

**Comment by OTL** [comment]
OMG!

**Comment by kaaatsu32329** [comment]
We can access the site instead with this URL (https://openrr.github.io/openrr-tutorial/en/html/)
